/**
 * withFokusWidget — Expo config plugin that wires a WidgetKit extension into
 * the iOS project generated by `expo prebuild`.
 *
 * On each prebuild it (idempotently):
 *   1. Adds the App Group entitlement `group.com.example.fokus` to the main app.
 *   2. Copies everything in `target/FokusWidget/` into `ios/FokusWidget/`.
 *   3. Writes per-target entitlements for the widget (`FokusWidget.entitlements`).
 *   4. Writes a React Native bridge (Swift + Obj-C shim) into the main app
 *      sources so JS can call `NativeModules.FokusWidgetBridge.updateData(json)`.
 *      The bridge writes the JSON to shared `UserDefaults(suiteName:)` and asks
 *      WidgetKit to reload all timelines.
 *   5. Registers an `app-extension` target named `FokusWidget` in the .pbxproj
 *      with the right build settings, frameworks (`WidgetKit`, `SwiftUI`), and
 *      iOS 17 deployment target.
 *
 * It is safe to run the plugin multiple times; it will not duplicate targets,
 * files, or build phases.
 */

const fs = require("fs");
const path = require("path");
const {
  withEntitlementsPlist,
  withInfoPlist,
  withXcodeProject,
  withDangerousMod,
} = require("expo/config-plugins");

const WIDGET_NAME = "FokusWidget";
const APP_GROUP = "group.com.example.fokus";
const DEPLOYMENT_TARGET = "17.0";

function ensureAppGroup(entitlements) {
  const key = "com.apple.security.application-groups";
  const existing = Array.isArray(entitlements[key]) ? entitlements[key] : [];
  if (!existing.includes(APP_GROUP)) {
    entitlements[key] = [...existing, APP_GROUP];
  }
  return entitlements;
}

function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(s, d);
    } else if (entry.isFile()) {
      fs.copyFileSync(s, d);
    }
  }
}

const WIDGET_ENTITLEMENTS = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${APP_GROUP}</string>
  </array>
</dict>
</plist>
`;

const BRIDGE_SWIFT = `// Auto-generated by plugins/withFokusWidget.js — do not edit.
import Foundation
import WidgetKit
#if canImport(ActivityKit)
import ActivityKit
#endif

@objc(FokusWidgetBridge)
class FokusWidgetBridge: NSObject {
  @objc static func requiresMainQueueSetup() -> Bool {
    return false
  }

  // MARK: - Home Screen widget data

  @objc(updateData:)
  func updateData(_ json: String) {
    let defaults = UserDefaults(suiteName: "${APP_GROUP}")
    defaults?.set(json, forKey: "fokusData")
    defaults?.synchronize()
    if #available(iOS 14.0, *) {
      WidgetCenter.shared.reloadAllTimelines()
    }
  }

  // MARK: - Live Activities (iOS 16.2+)
  //
  // We require iOS 16.2 for Live Activities because that's the first version
  // with the non-deprecated ActivityContent-based API. Devices on 16.1 fall
  // through to the false resolve so JS never blocks on the call.

  @objc(areLiveActivitiesEnabled:rejecter:)
  func areLiveActivitiesEnabled(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    #if canImport(ActivityKit)
    if #available(iOS 16.2, *) {
      resolve(ActivityAuthorizationInfo().areActivitiesEnabled)
      return
    }
    #endif
    resolve(false)
  }

  /// Starts a new Live Activity. Returns the activity id on success so JS can
  /// later update or end it. Always ends any pre-existing FokusActivity first
  /// so we never have two simultaneous activities.
  @objc(startLiveActivity:resolver:rejecter:)
  func startLiveActivity(
    _ json: String,
    resolver resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    #if canImport(ActivityKit)
    if #available(iOS 16.2, *) {
      Self._startLiveActivity(json, resolve: resolve, reject: reject)
      return
    }
    #endif
    reject("unsupported", "Live Activities require iOS 16.2 or later.", nil)
  }

  /// Updates every running FokusActivity in-place. Cheap because there's only
  /// ever one (see startLiveActivity).
  @objc(updateLiveActivity:resolver:rejecter:)
  func updateLiveActivity(
    _ json: String,
    resolver resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    #if canImport(ActivityKit)
    if #available(iOS 16.2, *) {
      Self._updateLiveActivity(json, resolve: resolve, reject: reject)
      return
    }
    #endif
    resolve(false)
  }

  /// Ends every running FokusActivity immediately.
  @objc(endLiveActivity:rejecter:)
  func endLiveActivity(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    #if canImport(ActivityKit)
    if #available(iOS 16.2, *) {
      Self._endLiveActivity(resolve: resolve)
      return
    }
    #endif
    resolve(false)
  }

  @objc(hasActiveLiveActivity:rejecter:)
  func hasActiveLiveActivity(
    _ resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    #if canImport(ActivityKit)
    if #available(iOS 16.2, *) {
      resolve(!Activity<FokusActivityAttributes>.activities.isEmpty)
      return
    }
    #endif
    resolve(false)
  }

  // MARK: - Implementation (iOS 16.2+ only)

  #if canImport(ActivityKit)
  @available(iOS 16.2, *)
  private static func _startLiveActivity(
    _ json: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let data = json.data(using: .utf8),
          let payload = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let text = payload["text"] as? String,
          let category = payload["category"] as? String else {
      reject("invalid_payload", "startLiveActivity expected { text, category }.", nil)
      return
    }

    guard ActivityAuthorizationInfo().areActivitiesEnabled else {
      reject("unauthorized", "Live Activities are disabled for this app.", nil)
      return
    }

    Task {
      for existing in Activity<FokusActivityAttributes>.activities {
        await existing.end(nil, dismissalPolicy: .immediate)
      }

      let sessionId = UUID().uuidString
      let attributes = FokusActivityAttributes(sessionId: sessionId)
      let state = FokusActivityAttributes.ContentState(
        text: text,
        category: category,
        startedAt: Date()
      )
      do {
        let activity = try Activity<FokusActivityAttributes>.request(
          attributes: attributes,
          content: .init(state: state, staleDate: nil),
          pushType: nil
        )
        resolve(activity.id)
      } catch {
        reject("start_failed", "Failed to start Live Activity: \\(error.localizedDescription)", nil)
      }
    }
  }

  @available(iOS 16.2, *)
  private static func _updateLiveActivity(
    _ json: String,
    resolve: @escaping RCTPromiseResolveBlock,
    reject: @escaping RCTPromiseRejectBlock
  ) {
    guard let data = json.data(using: .utf8),
          let payload = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
          let text = payload["text"] as? String,
          let category = payload["category"] as? String else {
      reject("invalid_payload", "updateLiveActivity expected { text, category }.", nil)
      return
    }
    Task {
      var updated = false
      for activity in Activity<FokusActivityAttributes>.activities {
        let state = FokusActivityAttributes.ContentState(
          text: text,
          category: category,
          startedAt: activity.content.state.startedAt
        )
        await activity.update(.init(state: state, staleDate: nil))
        updated = true
      }
      resolve(updated)
    }
  }

  @available(iOS 16.2, *)
  private static func _endLiveActivity(resolve: @escaping RCTPromiseResolveBlock) {
    Task {
      for activity in Activity<FokusActivityAttributes>.activities {
        await activity.end(nil, dismissalPolicy: .immediate)
      }
      resolve(true)
    }
  }
  #endif
}
`;

const BRIDGE_OBJC = `// Auto-generated by plugins/withFokusWidget.js — do not edit.
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(FokusWidgetBridge, NSObject)

RCT_EXTERN_METHOD(updateData:(NSString *)json)

RCT_EXTERN_METHOD(areLiveActivitiesEnabled:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(startLiveActivity:(NSString *)json
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(updateLiveActivity:(NSString *)json
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(endLiveActivity:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(hasActiveLiveActivity:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

@end
`;

function findMainAppSourceDir(platformRoot, fallbackName) {
  const candidates = [];
  for (const entry of fs.readdirSync(platformRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const p = path.join(platformRoot, entry.name);
    const hasAppDelegate =
      fs.existsSync(path.join(p, "AppDelegate.swift")) ||
      fs.existsSync(path.join(p, "AppDelegate.mm")) ||
      fs.existsSync(path.join(p, "AppDelegate.m"));
    if (hasAppDelegate) candidates.push({ name: entry.name, path: p });
  }
  if (candidates.length === 0) {
    const fallback = path.join(platformRoot, fallbackName);
    fs.mkdirSync(fallback, { recursive: true });
    return { name: fallbackName, path: fallback };
  }
  // Prefer the one matching the fallback name if multiple exist.
  const exact = candidates.find((c) => c.name === fallbackName);
  return exact || candidates[0];
}

function copyWidgetSources(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot;
      const src = path.join(projectRoot, "target", WIDGET_NAME);
      const dest = path.join(platformRoot, WIDGET_NAME);

      if (!fs.existsSync(src)) {
        throw new Error(
          `[withFokusWidget] Expected widget source at ${src} — make sure target/${WIDGET_NAME}/ exists at the project root.`,
        );
      }

      copyDirSync(src, dest);
      fs.writeFileSync(
        path.join(dest, `${WIDGET_NAME}.entitlements`),
        WIDGET_ENTITLEMENTS,
        "utf8",
      );

      const appName = cfg.modRequest.projectName || cfg.name || "Fokus";
      const appDir = findMainAppSourceDir(platformRoot, appName);
      fs.writeFileSync(path.join(appDir.path, "FokusWidgetBridge.swift"), BRIDGE_SWIFT, "utf8");
      fs.writeFileSync(path.join(appDir.path, "FokusWidgetBridge.m"), BRIDGE_OBJC, "utf8");

      // Patch the auto-generated bridging header so our Swift sources can see
      // RCTPromiseResolveBlock/RCTPromiseRejectBlock from React.
      const bridgingHeaderPath = path.join(appDir.path, `${appDir.name}-Bridging-Header.h`);
      if (fs.existsSync(bridgingHeaderPath)) {
        const existing = fs.readFileSync(bridgingHeaderPath, "utf8");
        const importLine = "#import <React/RCTBridgeModule.h>";
        if (!existing.includes(importLine)) {
          fs.writeFileSync(
            bridgingHeaderPath,
            `${existing.trimEnd()}\n${importLine}\n`,
            "utf8",
          );
        }
      }

      // FokusActivityAttributes.swift must be compiled into BOTH the main app
      // target (which starts/ends activities) and the widget extension target
      // (which renders them). Apple's Live Activity APIs match by unqualified
      // type name, so duplicating the source file into both targets is the
      // supported approach. We copy the source-of-truth from target/ into
      // ios/Fokus/ and let the existing widget copy stay in ios/FokusWidget/.
      const attrsSource = path.join(src, "FokusActivityAttributes.swift");
      if (fs.existsSync(attrsSource)) {
        fs.copyFileSync(
          attrsSource,
          path.join(appDir.path, "FokusActivityAttributes.swift"),
        );
      }

      // Stash the resolved main-app source dir name so the Xcode mod can find it.
      cfg.modRequest.fokusAppSourceDirName = appDir.name;

      return cfg;
    },
  ]);
}

function findMainAppTargetUUID(project, appName) {
  const targets = project.pbxNativeTargetSection();
  for (const key of Object.keys(targets)) {
    if (key.endsWith("_comment")) continue;
    const t = targets[key];
    if (!t || typeof t !== "object") continue;
    if (t.productType && t.productType.includes("com.apple.product-type.application")) {
      return key;
    }
    if (t.name === appName) return key;
  }
  return null;
}

function findGroupUUIDByName(project, name) {
  const groups = project.hash.project.objects.PBXGroup || {};
  for (const key of Object.keys(groups)) {
    if (key.endsWith("_comment")) continue;
    const g = groups[key];
    if (!g || typeof g !== "object") continue;
    if (g.name === name || g.path === name) {
      return key;
    }
  }
  return null;
}

function alreadyHasFile(project, fileName, targetUUID) {
  const buildFiles = project.hash.project.objects.PBXBuildFile || {};
  for (const key of Object.keys(buildFiles)) {
    if (key.endsWith("_comment")) continue;
    const bf = buildFiles[key];
    if (!bf || typeof bf !== "object") continue;
    if (bf.fileRef_comment === fileName) return true;
  }
  // Also check file refs.
  const fileRefs = project.hash.project.objects.PBXFileReference || {};
  for (const key of Object.keys(fileRefs)) {
    if (key.endsWith("_comment")) continue;
    const fr = fileRefs[key];
    if (!fr || typeof fr !== "object") continue;
    if (fr.path === fileName || fr.name === fileName) return true;
  }
  return false;
}

function addBridgeFilesToMainTarget(project, appDirName, appName) {
  const mainTargetUUID = findMainAppTargetUUID(project, appName);
  if (!mainTargetUUID) {
    console.warn("[withFokusWidget] Could not locate the main app target.");
    return;
  }
  let mainGroupUUID =
    findGroupUUIDByName(project, appDirName) ||
    findGroupUUIDByName(project, appName);
  if (!mainGroupUUID) {
    console.warn(
      `[withFokusWidget] Could not locate PBXGroup for '${appDirName}'. Bridge files copied but not added to project.`,
    );
    return;
  }

  const filesToAdd = [
    "FokusWidgetBridge.swift",
    "FokusWidgetBridge.m",
    "FokusActivityAttributes.swift",
  ];
  for (const fileName of filesToAdd) {
    if (alreadyHasFile(project, fileName, mainTargetUUID)) continue;
    project.addSourceFile(
      `${appDirName}/${fileName}`,
      { target: mainTargetUUID },
      mainGroupUUID,
    );
  }
}

function registerExtensionTarget(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const platformRoot = cfg.modRequest.platformProjectRoot;
    const widgetRoot = path.join(platformRoot, WIDGET_NAME);
    const appName = cfg.modRequest.projectName || cfg.name || "Fokus";
    const appDirName = cfg.modRequest.fokusAppSourceDirName || appName;
    const bundleIdentifier =
      (cfg.ios && cfg.ios.bundleIdentifier) || "com.example.fokus";
    const widgetBundleId = `${bundleIdentifier}.${WIDGET_NAME.toLowerCase()}`;

    // 1) Make sure the bridge files belong to the main app target.
    addBridgeFilesToMainTarget(project, appDirName, appName);

    // 2) Bail out idempotently if the widget extension target already exists.
    const existingTargets = project.pbxNativeTargetSection();
    for (const key of Object.keys(existingTargets)) {
      if (key.endsWith("_comment")) continue;
      const target = existingTargets[key];
      if (target && typeof target === "object" && target.name === WIDGET_NAME) {
        return cfg;
      }
    }

    // 3) Add the extension target.
    const target = project.addTarget(
      WIDGET_NAME,
      "app_extension",
      WIDGET_NAME,
      widgetBundleId,
    );

    project.addBuildPhase([], "PBXSourcesBuildPhase", "Sources", target.uuid);
    project.addBuildPhase([], "PBXResourcesBuildPhase", "Resources", target.uuid);
    project.addBuildPhase(
      ["SwiftUI.framework", "WidgetKit.framework"],
      "PBXFrameworksBuildPhase",
      "Frameworks",
      target.uuid,
    );

    const pbxGroup = project.addPbxGroup(
      [],
      WIDGET_NAME,
      WIDGET_NAME,
      '"<group>"',
    );

    // Attach the new group to the top-level project group.
    const groups = project.hash.project.objects.PBXGroup || {};
    Object.keys(groups).forEach((key) => {
      if (key.endsWith("_comment")) return;
      const g = groups[key];
      if (!g || typeof g !== "object") return;
      if (g.name === undefined && g.path === undefined) {
        project.addToPbxGroup(pbxGroup.uuid, key);
      }
    });

    // 4) Walk the widget folder and add each file to the right phase. The
    //    parent PBXGroup already carries `path = "FokusWidget"`, so file refs
    //    only need the bare filename (otherwise xcode doubles the prefix).
    for (const entry of fs.readdirSync(widgetRoot, { withFileTypes: true })) {
      if (!entry.isFile()) continue;
      const fileName = entry.name;
      if (fileName.endsWith(".swift")) {
        project.addSourceFile(fileName, { target: target.uuid }, pbxGroup.uuid);
      } else if (fileName === "Info.plist" || fileName.endsWith(".entitlements")) {
        project.addFile(fileName, pbxGroup.uuid, { target: target.uuid });
      } else {
        project.addResourceFile(fileName, { target: target.uuid }, pbxGroup.uuid);
      }
    }

    // 5) Set build settings on every configuration for the new target.
    const configurations = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      if (key.endsWith("_comment")) continue;
      const obj = configurations[key];
      if (!obj || typeof obj !== "object") continue;
      if (
        typeof obj.buildSettings !== "undefined" &&
        obj.buildSettings.PRODUCT_NAME === `"${WIDGET_NAME}"`
      ) {
        const bs = obj.buildSettings;
        bs.CLANG_ENABLE_MODULES = "YES";
        bs.INFOPLIST_FILE = `"${WIDGET_NAME}/Info.plist"`;
        bs.CODE_SIGN_ENTITLEMENTS = `"${WIDGET_NAME}/${WIDGET_NAME}.entitlements"`;
        bs.CODE_SIGN_STYLE = "Automatic";
        bs.CURRENT_PROJECT_VERSION = '"1"';
        bs.GENERATE_INFOPLIST_FILE = "NO";
        bs.MARKETING_VERSION = '"1.0"';
        bs.IPHONEOS_DEPLOYMENT_TARGET = DEPLOYMENT_TARGET;
        bs.PRODUCT_BUNDLE_IDENTIFIER = `"${widgetBundleId}"`;
        bs.SKIP_INSTALL = "YES";
        bs.SWIFT_VERSION = "5.0";
        bs.TARGETED_DEVICE_FAMILY = '"1,2"';
        bs.LD_RUNPATH_SEARCH_PATHS =
          '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"';
      }
    }

    return cfg;
  });
}

module.exports = function withFokusWidget(config) {
  config = withEntitlementsPlist(config, (cfg) => {
    cfg.modResults = ensureAppGroup(cfg.modResults || {});
    return cfg;
  });
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults = cfg.modResults || {};
    // Required for ActivityKit (Live Activities) to be allowed in the app.
    cfg.modResults.NSSupportsLiveActivities = true;
    return cfg;
  });
  config = copyWidgetSources(config);
  config = registerExtensionTarget(config);
  return config;
};
